# Lab Task 01

Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

Concatenate two NumPy arrays horizontally and vertically.

In [5]:
#code here
import numpy as np
arr = np.arange(12)
print('Original: \n', arr)
arr = arr.reshape(3,4)
print('\nReshaped: \n', arr)


Original: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [6]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Horizontally
horizontal = np.concatenate((array1, array2), axis=1)
print("Horizontally: \n", horizontal)

# Vertically
vertical = np.concatenate((array1, array2), axis=0)
print("\nVertically: \n", vertical)


Horizontally: 
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]

Vertically: 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# Lab Task 02


## Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [9]:
#code here
import string
def classify_emails(emails):
  punctuation  = string.punctuation
  important_keywords = ['Urgent', 'Important', 'Action required',
                        'Immediate attention', 'Critical', 'Deadline', 'Emergency',
                        'Priority', 'Time-sensitive', 'Response needed']
  promotions_keywords = ['Sale', 'Discount', 'Offer', 'Deal', 'Special',
                          'Clearance', 'Limited time', 'Exclusive',
                          'Savings', 'Coupon']
  spam_keywords = ['Lottery', 'Inheritance', 'Free', 'Cash prize',
                    'Guaranteed', 'Congratulations', 'Click here',
                    'Unsubscribe', 'Nigerian prince']
  important = []
  promotions = []
  spam = []

  for email in emails:
      lower = email.lower()
      if any(word.lower() in lower for word in important_keywords):
          important.append(email)
      elif any(word.lower() in lower for word in promotions_keywords):
          promotions.append(email)
      elif any(word.lower() in lower for word in spam_keywords):
          spam.append(email)

  return important, promotions, spam



In [10]:
emails = [
    "Important: Action Required",
    "Special Discount Offer",
    "You won the lottery!",
    "Urgent: Response Needed",
    "Inheritance Notification",
    "Viagra for sale"
]
important, promotions, spam = classify_emails(emails)

print("Important Emails:", important)
print("Promotions Emails:", promotions)
print("Spam Emails:", spam)

Important Emails: ['Important: Action Required', 'Urgent: Response Needed']
Promotions Emails: ['Special Discount Offer', 'Viagra for sale']
Spam Emails: ['You won the lottery!', 'Inheritance Notification']


# Lab Task 03

## English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [14]:
#code here
# English-Spanish dictionary
english_spanish_dict = {
    'hello': 'hola',
    'goodbye': 'adiós',
    'thank you': 'gracias',
    'please': 'por favor',
    'sorry': 'lo siento',
    'yes': 'sí',
    'no': 'no',
    'apple': 'manzana',
    'banana': 'plátano',
    'cat': 'gato',
    'dog': 'perro'
}

while True:
    word = input("Enter English word (/type 'exit' to quit): ")
    # If Exit
    if word.lower() == 'exit':
        print("Exiting the dictionary. Goodbye!")
        break

    if word in english_spanish_dict:
        print(f"The Spanish of '{word}' is '{english_spanish_dict[word]}'.")
    else:
        print(f"Sorry, the translation of '{word}' is not available in the dictionary.")


Enter English word (/type 'exit' to quit): hello
The Spanish of 'hello' is 'hola'.
Enter English word (/type 'exit' to quit): ye
Sorry, the translation of 'ye' is not available in the dictionary.
Enter English word (/type 'exit' to quit): yes
The Spanish of 'yes' is 'sí'.
Enter English word (/type 'exit' to quit): exit
Exiting the dictionary. Goodbye!


# Lab Task 04

dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

Some tree example

In [15]:
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv")
df


Rank                                              Name Platform  \
0          1                                        Wii Sports      Wii   
1          2                                 Super Mario Bros.      NES   
2          3                                    Mario Kart Wii      Wii   
3          4                                 Wii Sports Resort      Wii   
4          5                          Pokemon Red/Pokemon Blue       GB   
...      ...                                               ...      ...   
16593  16596                Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                     Men in Black II: Alien Escape       GC   
16595  16598  SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                        Know How 2       DS   
16597  16600                                  Spirits & Spells      GBA   

         Year         Genre   Publisher  NA_Sales  EU_Sales  JP_Sales  \
0      2006.0        Sports    Nintendo     41.49     29.02      3.77   
1      1985.0      Platform    Nintendo     29.08      3.58      6.81   
2      2008.0        Racing    Nintendo     15.85     12.88      3.79   
3      2009.0        Sports    Nintendo     15.75     11.01      3.28   
4      1996.0  Role-Playing    Nintendo     11.27      8.89     10.22   
...       ...           ...         ...       ...       ...       ...   
16593  2002.0      Platform       Kemco      0.01      0.00      0.00   
16594  2003.0       Shooter  Infogrames      0.01      0.00      0.00   
16595  2008.0        Racing  Activision      0.00      0.00      0.00   
16596  2010.0        Puzzle    7G//AMES      0.00      0.01      0.00   
16597  2003.0      Platform     Wanadoo      0.01      0.00      0.00   

       Other_Sales  Global_Sales  
0             8.46         82.74  
1             0.77         40.24  
2             3.31         35.82  
3             2.96         33.00  
4             1.00         31.37  
...            ...           ...  
16593         0.00          0.01  
16594         0.00          0.01  
16595         0.00          0.01  
16596         0.00          0.01  
16597         0.00          0.01  

[16598 rows x 11 columns]

In [16]:
globalSales = df['Global_Sales'].sum()
print("Total global sales for all games:", globalSales)

Total global sales for all games: 8920.44


In [31]:
highestSale = df.loc[df['Global_Sales'].idxmax()]
print("Game with the highest global sales:")
print(highestSale)

Game with the highest global sales:
Rank                     1
Name            Wii Sports
Platform               Wii
Year                2006.0
Genre               Sports
Publisher         Nintendo
NA_Sales             41.49
EU_Sales             29.02
JP_Sales              3.77
Other_Sales           8.46
Global_Sales         82.74
Name: 0, dtype: object


In [22]:
# Determine the average sales for each region
avgSales = df[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].mean()
print("Average sales for each region:\n", avgSales)

Average sales for each region:
 NA_Sales       0.264667
EU_Sales       0.146652
JP_Sales       0.077782
Other_Sales    0.048063
dtype: float64


In [30]:
top5Genres = df.groupby('Genre')['Global_Sales'].sum().nlargest(5)
print("5 most popular genres based on global sales:")
print(top5Genres)

5 most popular genres based on global sales:
Genre
Action          1751.18
Sports          1330.93
Shooter         1037.37
Role-Playing     927.37
Platform         831.37
Name: Global_Sales, dtype: float64


In [24]:
totalPrRegion = df.groupby('Genre')[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].sum()
pop = totalPrRegion['NA_Sales'].idxmax()
print("Most popular genre in North America:", pop)

Most popular genre in North America: Action


In [25]:
df.tail(10)

Rank                                               Name Platform  \
16588  16591                                   Mega Brain Boost       DS   
16589  16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV   
16590  16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP   
16591  16594                                Myst IV: Revelation       PC   
16592  16595                                           Plushees       DS   
16593  16596                 Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                      Men in Black II: Alien Escape       GC   
16595  16598   SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                         Know How 2       DS   
16597  16600                                   Spirits & Spells      GBA   

         Year         Genre              Publisher  NA_Sales  EU_Sales  \
16588  2008.0        Puzzle  Majesco Entertainment      0.01      0.00   
16589  2016.0        Action        dramatic create      0.00      0.00   
16590  2007.0  Role-Playing     Falcom Corporation      0.00      0.00   
16591  2004.0     Adventure                Ubisoft      0.01      0.00   
16592  2008.0    Simulation              Destineer      0.01      0.00   
16593  2002.0      Platform                  Kemco      0.01      0.00   
16594  2003.0       Shooter             Infogrames      0.01      0.00   
16595  2008.0        Racing             Activision      0.00      0.00   
16596  2010.0        Puzzle               7G//AMES      0.00      0.01   
16597  2003.0      Platform                Wanadoo      0.01      0.00   

       JP_Sales  Other_Sales  Global_Sales  
16588      0.00          0.0          0.01  
16589      0.01          0.0          0.01  
16590      0.01          0.0          0.01  
16591      0.00          0.0          0.01  
16592      0.00          0.0          0.01  
16593      0.00          0.0          0.01  
16594      0.00          0.0          0.01  
16595      0.00          0.0          0.01  
16596      0.00          0.0          0.01  
16597      0.00          0.0          0.01

In [29]:
top = df.groupby('Platform')['Global_Sales'].sum().nlargest(3)
print("Top 3 platforms with the highest global sales:")
print(top)

Top 3 platforms with the highest global sales:
Platform
PS2     1255.64
X360     979.96
PS3      957.84
Name: Global_Sales, dtype: float64


In [32]:
total = df['Global_Sales'].sum()
share = (df.groupby('Genre')['Global_Sales'].sum() / total) * 100
print("Market share for each genre:")
print(share)


Market share for each genre:
Genre
Action          19.631094
Adventure        2.679688
Fighting         5.032375
Misc             9.079821
Platform         9.319832
Puzzle           2.745941
Racing           8.206322
Role-Playing    10.396012
Shooter         11.629135
Simulation       4.396644
Sports          14.920004
Strategy         1.963132
Name: Global_Sales, dtype: float64


In [34]:
corCoefficient = df['NA_Sales'].corr(df['EU_Sales'])
print("Correlation coefficient between NA & EU:", corCoefficient)

Correlation coefficient between NA & EU: 0.7677267483702631


In [ ]:
# import pandas as pd

# # Create a DataFrame to represent a tree
# data = {
#     'node': ['A', 'B', 'C', 'D', 'E', 'F'],
#     'parent': [None, 'A', 'A', 'B', 'B', 'C']
# }
# df = pd.DataFrame(data)

# print(df)


In [ ]:
# pip install networkx


In [ ]:
# import pandas as pd
# import networkx as nx
# import matplotlib.pyplot as plt

# # Create a DataFrame representing edges in a graph
# data = {
#     'from': ['A', 'A', 'B', 'C', 'D'],
#     'to': ['B', 'C', 'D', 'E', 'E']
# }
# edges = pd.DataFrame(data)

# # Create a graph from the edges DataFrame
# G = nx.from_pandas_edgelist(edges, 'from', 'to')

# # Draw the graph
# nx.draw(G, with_labels=True)
# plt.show()

# # Analyze the graph
# print("Nodes:", G.nodes())
# print("Edges:", G.edges())
# print("Degree for each Node:", dict(G.degree()))
